spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://172.75.0.3:5432/postgres
    username: postgres
    password: toor

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

okta:
  oauth2:
    issuer: https://dev-06452185.okta.com/oauth2/default
    clientId: 0oa58cfs2n8G5gu7N5d7
    clientSecret: K-P8ZH0nZ5OOlUkizCeSrKbdr1Oa2Ps491XEx53U
    scope: openid profile email