spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://172.75.0.3:5432/postgres
    username: postgres
    password: toor

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus